#!/usr/bin/env bash
# script to transfer files from local to remote server
# Strict host key checking must be disabled when using scp

if [ $# -lt 4 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
    sudo scp -i $4 $1 $3@$2:~/ && echo "File transferred!"
fi
