#!/usr/bin/env bash
# this script is so that /redirect_me will redirect to another page

# Install Nginx web server
sudo apt-get update
sudo apt-get install -y nginx

# Configure Nginx to redirect /redirect_me to another page with 301 status
sudo sed -i '/listen 80 default_server;/a \\n\tlocation /redirect_me {\n\t\treturn 301 https://www.google.com;\n\t}' /etc/nginx/sites-available/default

# Restart Nginx
sudo service nginx restart
