#!/usr/bin/env bash
# this script is so that /redirect_me will redirect to another page

# Install Nginx web server
sudo apt-get update
sudo apt-get install -y nginx

# Creating an index.html page
echo "Hello World!" | sudo tee /var/www/html/index.html

# Performing a 301 Redirection
string_replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/googel.com\/besthor permanent;"
sudo sed -i "s/server_name _;/$string_replacement/" /etc/nginx/sites-enabled/default

# Restart Nginx
sudo service nginx restart
