#!/usr/bin/env bash
# return a 404 page

# Updating Packages and install nginx
sudo apt-get update
sudo apt-get install -y nginx

# Creating index.html page
echo "Hello World!" | sudo tee /var/www/html/index.html

# "moved permanently redirection" with a (301) status
string="server_name _;\n\trewrite ^\/redirect_me https:\/\/google.com\/besthor permanent;"
sudo sed -i "s/server_name _;/$string/" /etc/nginx/sites-enabled/default

# Creating a 404 page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
new_string="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"

sudo sed -i "s/listen 80 default_server;/$new_string/" /etc/nginx/sites-enabled/default

# Testing syntax
sudo nginx -t

# restart nginx after implementing changes
sudo service nginx restart
