#!/usr/bin/env bash
# This script prints "Best school" but prints "Hi" if i = 9

for i in $(seq 0 10); do
    if [ "$i" -eq 9 ]; then
        echo "Hi"
    else
        echo "Best School"
    fi
done

