#!/usr/bin/env bash
# echo bad luck if i =4, good luck if i = 8, else echo "Best school"

i=1
while [ $i -le 10 ]
do
	if [ $i -eq 4 ]; then
		echo "bad luck"
	elif [ $i -eq 8 ]; then
		echo "good luck"
	else
		echo "Best School"
	fi
	i=$(( i+1 ))
done
