#!/usr/bin/env bash
# disply list of files in directory with out the first dash

files=$(ls)
for file in $files; do
    name_after_dash=$(echo "$file" | cut -d '-' -f 2-)
    echo "$name_after_dash"
done
