#!/usr/bin/env bash
# connect to a server using ssh

# variables
server="35.153.232.142"
private_key="~/.ssh/school"
user="ubuntu"

# Connect to the server using ssh
ssh -i "$private_key" "$user"@"$server"
