#!/usr/bin/env bash
# create an ssh key pair with a passphrase

# variables
key_name="school"
key_bits="4096"
passphrase="betty"

# Create RSA key pair
ssh-keygen -t rsa -b "$key_bits" -f "$key_name" -N "$passphrase"
